Add monitoring alerts
ebi-ait/ingest-kube-deployment pull request #25
Opened 2021-07-02 13:59 UTC by jacobwindsor

- Adds alerts to the monitoring dashboard
  - If a pod fails
  - If ingest-core memory usage is coming close to the maximum
  - If we are coming close to the number of pods allowed on a node (70), the threshold for alert set at 65
  - If the replica count of ingest-exporter exceeds 10
- Adds a slack notification channel to report alerts to #hca-ingest-dev-notifications
- Makes it easier to deploy changes to the monitoring dashboard

2021-07-02 13:59 UTC, jacobwindsor commented
FYI these changes are already deployed to the monitoring environments. I did that for testing purposes.

2021-07-02 14:08 UTC, ke4 approved these changes
Looks fine with me 👍

2021-07-02 14:46 UTC, amnonkhen approved these changes

2021-07-02 14:50 UTC, amnonkhen requested changes
The readme files seems to be getting very large. I would split.

2021-07-02 14:50 UTC, amnonkhen commented on README.md
>  ### Upgrading Ingest Monitoring Dashboard
Why is the **monitoring** section under the U**pgrade Backend Services** section?

2021-07-05 12:55 UTC, jacobwindsor commented
@amnonkhen split how? Into multiple READMEs?

2021-07-14 08:53 UTC, amnonkhen approved these changes

2021-07-14 09:28 UTC, merged